version: '3'
services:
  biliup:
    build: .
    container_name: biliup-self
    restart: unless-stopped
    ports:
      - "<HOST_ADDRESS>:<HOST_PORT>:19159"
    volumes:
      - /path/to/save_folder:/opt
    command: server --auth
